[package]
name = "porgi"
version = "0.1.0"
edition = "2021"

description = "A simple cli TUI for finding and organizing your code projects"

license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.4"
color-eyre = "0.6.3"
crossterm = "0.27.0"
dirs = "5.0.1"
eyre = "0.6.12"
git2 = "0.18.3"
itertools = "0.12.1"
ratatui = "0.26.2"
rayon = "1.10.0"
serde = { version = "1.0.200", features = ["derive"] }
shellexpand = "3.1.0"
toml = "0.8.12"
walkdir = "2.5.0"
