[package]
name = "projects"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.4"
color-eyre = "0.6.3"
crossterm = "0.27.0"
dirs = "5.0.1"
eyre = "0.6.12"
git2 = "0.18.3"
itertools = "0.12.1"
ratatui = "0.26.2"
serde = { version = "1.0.200", features = ["derive"] }
shellexpand = "3.1.0"
toml = "0.8.12"
